### ISSUE TITLE
IVRs timeout behaviour makes no sense to me

### ISSUE THREAD

**Issue by manfer** [irontec/ivozprovider#275]
First two things.

If I'm not wrong in custom IVRs -where it is not allowed to dial an extension- makes no sense the no answer route. It never happens the way custom IVR is coded and it is confusing.

Max length makes no sense either in custom IVRs and it is very very confusing until you realize it. Custom IVRs only allow 1 digit -if you dial more than one digit only the last one is taken into account-. So custom IVRs only allow 0-9 as input.

It would be a lot better if those options are removed -just hidden should be enough-. It would be easier to understand.

----------------------------

All IVRs I have seen consider the no answer route as the route to follow when the caller dials nothing.

But the way this route is coded is as the one to follow when the extension does not answer the call which should not be something that the IVR handles but the user itself. In fact users already have forward settings (and those ones should be enhanced, in my opinion, if they can't handle this situation from IVRs -external calls-). The IVR should just transfer the call to the user and die. 

Besides, as it is coded now, the route that follows when the caller dials nothing is the error route.

So there is no way to separate two different common cases -most often used routes, in my opinion- that are present on any IVR I have seen,

- When caller dials a non existing extension (error).- Common route to follow in this case is the IVR itself to repeat the prompt. I have even seen this only allowed x times. After x times the route would be just hang out.
- When caller dials nothing (timeout).- Most of the time the call is routed to a receptionist (not a virtual one)

----------------------------

There is an issue that suggests joining both IVRs into just one. Something I think would be a good idea.

In the meanwhile I would suggest hiding those options on custom IVRs that do nothing if I understand them correctly.

**Comment by cruzccl** [comment]
Hi @manfer ,

IVR sections need a lot of work, you are right. There a few related issues:

- #180 for merging both sections.

- #182 for different actions for no input and wrong input.

Besides, there was a bug with the way Action if timeout was implemented (fixed in #276).

We have improved documentation of IVRs to explain 2 more things appropiately via #277:

- Action if timeout only applies for calls to users (extensions that point to user in IVR common and entries that point to extensions that point to user).

- Entries in custom IVRs are regular expression.

Read [modified IVR section](https://irontec.github.io/ivozprovider/en/pbx_features/ivrs.html) for further information.

Regards,

**Comment by manfer** [comment]
Hi @cruzccl ,

Thanks for the clarification and the fix.

I was trying some of the options incorrectly. I was mixing regular and non regular expressions in custom IVRs.

After reading the new documentation makes more sense now. I didn't realize on custom IVRs it was allowed to dial an extension too.

Still not sure about the no input route after reading doc. That is still not implemented, isn't it?

**Comment by cruzccl** [comment]
If you mean making different the no input and the error behaviour, no, it's not done yet but is in the roadmap in #182 .

Regards,

**Comment by Kaian** [comment]
Since 1.6.2 noAnswer handler will be removed and calling an extension from an IVR will be the same as calling the extension directly: same effect, same handlers, and same result.

We have revamped those fields for No Input handler, so now different logics can be implemented for Nothing entered and Wrong value entered.

We will strive to implement #180 in the next major release, but current one will keep IVRs just as they are, so I'm closing this.

Feel free to add any related feedback or reopen the issue.

Regards,
